# This is a config for E2B sandbox template.
# You can use template ID (bxq9sha9l55ytsyfturr) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("bxq9sha9l55ytsyfturr") # Sync sandbox
# sandbox = await AsyncSandbox.create("bxq9sha9l55ytsyfturr") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('bxq9sha9l55ytsyfturr')

start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "bxq9sha9l55ytsyfturr"